// UIActivityIndicatorViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension SwiftCocoaDSL where Base :UIActivityIndicatorView {
    @discardableResult
    public func activityIndicatorViewStyle(_ activityIndicatorViewStyle: UIActivityIndicatorViewStyle) -> Self {
        base.activityIndicatorViewStyle = activityIndicatorViewStyle
        return self
    }

    @discardableResult
    public func hidesWhenStopped(_ hidesWhenStopped: Bool) -> Self {
        base.hidesWhenStopped = hidesWhenStopped
        return self
    }

    @discardableResult
    public func color(_ color: UIColor) -> Self {
        base.color = color
        return self
    }
}
