// UIActivityIndicatorViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension UIActivityIndicatorView {
    @discardableResult
    func activityIndicatorViewStyle(_ activityIndicatorViewStyle: UIActivityIndicatorViewStyle) -> Self {
        self.activityIndicatorViewStyle = activityIndicatorViewStyle
        return self
    }

    @discardableResult
    func hidesWhenStopped(_ hidesWhenStopped: Bool) -> Self {
        self.hidesWhenStopped = hidesWhenStopped
        return self
    }

    @discardableResult
    func color(_ color: UIColor) -> Self {
        self.color = color
        return self
    }
}
