// UIAlertViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension SwiftCocoaDSL where Base :UIAlertView {
    @discardableResult
    public func title(_ title: String) -> Self {
        base.title = title
        return self
    }

    @discardableResult
    public func message(_ message: String) -> Self {
        base.message = message
        return self
    }

    @discardableResult
    public func cancelButtonIndex(_ cancelButtonIndex: Int) -> Self {
        base.cancelButtonIndex = cancelButtonIndex
        return self
    }

    @discardableResult
    public func alertViewStyle(_ alertViewStyle: UIAlertViewStyle) -> Self {
        base.alertViewStyle = alertViewStyle
        return self
    }
}
