// UIImageViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension UIImageView {
    @discardableResult
    func image(_ image: UIImage) -> Self {
        self.image = image
        return self
    }

    @discardableResult
    func highlightedImage(_ highlightedImage: UIImage) -> Self {
        self.highlightedImage = highlightedImage
        return self
    }

    @discardableResult
    func userInteractionEnabled(_ isUserInteractionEnabled: Bool) -> Self {
        self.isUserInteractionEnabled = isUserInteractionEnabled
        return self
    }

    @discardableResult
    func isHighlighted(_ isHighlighted: Bool) -> Self {
        self.isHighlighted = isHighlighted
        return self
    }

    @discardableResult
    func animationDuration(_ animationDuration: TimeInterval) -> Self {
        self.animationDuration = animationDuration
        return self
    }

    @discardableResult
    func animationRepeatCount(_ animationRepeatCount: Int) -> Self {
        self.animationRepeatCount = animationRepeatCount
        return self
    }
}
