// UIImageViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension SwiftCocoaDSL where Base :UIImageView {
    @discardableResult
    public func image(_ image: UIImage) -> Self {
        base.image = image
        return self
    }

    @discardableResult
    public func highlightedImage(_ highlightedImage: UIImage) -> Self {
        base.highlightedImage = highlightedImage
        return self
    }

    @discardableResult
    public func userInteractionEnabled(_ isUserInteractionEnabled: Bool) -> Self {
        base.isUserInteractionEnabled = isUserInteractionEnabled
        return self
    }

    @discardableResult
    public func isHighlighted(_ isHighlighted: Bool) -> Self {
        base.isHighlighted = isHighlighted
        return self
    }

    @discardableResult
    public func animationDuration(_ animationDuration: TimeInterval) -> Self {
        base.animationDuration = animationDuration
        return self
    }

    @discardableResult
    public func animationRepeatCount(_ animationRepeatCount: Int) -> Self {
        base.animationRepeatCount = animationRepeatCount
        return self
    }
}
