// UIPopoverBackgroundViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension SwiftCocoaDSL where Base :UIPopoverBackgroundView {
    @discardableResult
    public func arrowOffset(_ arrowOffset: CGFloat) -> Self {
        base.arrowOffset = arrowOffset
        return self
    }

    @discardableResult
    public func arrowDirection(_ arrowDirection: UIPopoverArrowDirection) -> Self {
        base.arrowDirection = arrowDirection
        return self
    }
}
