// UIPopoverBackgroundViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension UIPopoverBackgroundView {
    @discardableResult
    func arrowOffset(_ arrowOffset: CGFloat) -> Self {
        self.arrowOffset = arrowOffset
        return self
    }

    @discardableResult
    func arrowDirection(_ arrowDirection: UIPopoverArrowDirection) -> Self {
        self.arrowDirection = arrowDirection
        return self
    }
}
