// UIStackViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension SwiftCocoaDSL where Base :UIStackView {
    @discardableResult
    public func axis(_ axis: UILayoutConstraintAxis) -> Self {
        base.axis = axis
        return self
    }

    @discardableResult
    public func distribution(_ distribution: UIStackViewDistribution) -> Self {
        base.distribution = distribution
        return self
    }

    @discardableResult
    public func alignment(_ alignment: UIStackViewAlignment) -> Self {
        base.alignment = alignment
        return self
    }

    @discardableResult
    public func spacing(_ spacing: CGFloat) -> Self {
        base.spacing = spacing
        return self
    }

    @discardableResult
    public func baselineRelativeArrangement(_ baselineRelativeArrangement: Bool) -> Self {
        base.isBaselineRelativeArrangement = baselineRelativeArrangement
        return self
    }

    @discardableResult
    public func layoutMarginsRelativeArrangement(_ layoutMarginsRelativeArrangement: Bool) -> Self {
        base.isLayoutMarginsRelativeArrangement = layoutMarginsRelativeArrangement
        return self
    }
}
