// UIStackViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension UIStackView {
    @discardableResult
    func axis(_ axis: UILayoutConstraintAxis) -> Self {
        self.axis = axis
        return self
    }

    @discardableResult
    func distribution(_ distribution: UIStackViewDistribution) -> Self {
        self.distribution = distribution
        return self
    }

    @discardableResult
    func alignment(_ alignment: UIStackViewAlignment) -> Self {
        self.alignment = alignment
        return self
    }

    @discardableResult
    func spacing(_ spacing: CGFloat) -> Self {
        self.spacing = spacing
        return self
    }

    @discardableResult
    func baselineRelativeArrangement(_ baselineRelativeArrangement: Bool) -> Self {
        isBaselineRelativeArrangement = baselineRelativeArrangement
        return self
    }

    @discardableResult
    func layoutMarginsRelativeArrangement(_ layoutMarginsRelativeArrangement: Bool) -> Self {
        isLayoutMarginsRelativeArrangement = layoutMarginsRelativeArrangement
        return self
    }
}
