// UITableViewHeaderFooterViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension UITableViewHeaderFooterView {
    @discardableResult
    func backgroundView(_ backgroundView: UIView) -> Self {
        self.backgroundView = backgroundView
        return self
    }
}
