// UITableViewHeaderFooterViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension SwiftCocoaDSL where Base :UITableViewHeaderFooterView {
    @discardableResult
    public func backgroundView(_ backgroundView: UIView) -> Self {
        base.backgroundView = backgroundView
        return self
    }
}
