// UIVisualEffectViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension UIVisualEffectView {
    @discardableResult
    func effect(_ effect: UIVisualEffect) -> Self {
        self.effect = effect
        return self
    }
}
