// UIVisualEffectViewExtension.swift
// the Code is generated by https://github.com/hhfa008/SwiftAI

import UIKit
extension SwiftCocoaDSL where Base :UIVisualEffectView {
    @discardableResult
    public func effect(_ effect: UIVisualEffect) -> Self {
        base.effect = effect
        return self
    }
}
